config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    scope :question do
      namespace :listening, path: "/" do
        resources :listening_questions
        resources :conversation_questions
        resources :picture_questions
      end
      namespace :reading, path: "/" do
        resources :reading_questions
        resources :grammar_questions
        resources :sign_questions
        resources :paragraph_questions
      end
      namespace :writing, path: "/" do
        resources :writing_questions 
        resources :questions
      end
    end
    scope :exam do
      namespace :reading, path: "/" do
        resources :reading_exams
        resources :grammar_exams
      end
      namespace :listening, path: "/" do
        resources :listening_exams
      end
      namespace :writing, path: "/" do
        resources :writing_exams
      end
    end
  end
  get "listening", to: "listening#index"
  get "writing", to: "writing#index"
  get "listening", to: "listening#index"
  get "static_pages", to: "static_pages#index"
  get "reading", to: "reading#index"
  post "reading/exams", to: "reading#exams_by_topic"
  get "reading/show/:id", to: "reading#show"
  get "reading/work_space/:id", to: "reading#work_space"
  post "reading/exam_detail", to: "reading#exam_detail"
  post "reading/check_answer", to: "reading#check_answer"
end

app/controllers/admin/reading/grammar_exams_controller.rb
class Admin::Reading::GrammarExamsController < ApplicationController
  layout "admin/application"

  def new
    @grammar_exam = CreateNextExam.call Topic.codes[:grammar]
    @questions_not_in_exam = (Question.not_belong_to_exam Topic.codes[:grammar])
                             .page(params[:page])
                             .per Settings.Admin.grammar_exams.per_page
  end

  def create
    if CreateExam.call grammar_exam_params
      flash[:success] = t ".flash_success"
      redirect_to admin_reading_reading_exams_path
    else
      flash[:danger] = t ".flash_danger"
      redirect_to new_admin_reading_grammar_exam_path
    end
  end

  def destroy
    @exam = Exam.find_by id: params[:id]
    @question_types = @exam.question_types
    return unless @question_types.update_all exam_id: nil
    @exam.destroy
    flash[:success] = t ".flash"
    redirect_to request.referrer || root_url
  end

  private

  def grammar_exam_params
    exam = params.require(:exam)
    {name: exam[:name], question_ids: exam[:question_ids]}
  end
end

app/controllers/admin/reading/grammar_questions_controller.rb
class Admin::Reading::GrammarQuestionsController < ApplicationController
  layout "admin/application"
  before_action :find_question, except: %i(new create)
  before_action :not_belong_to_exam, only: %i(destroy)

  def new
    @question = Question.new
    Settings.Admin.grammar_question.num_answer
            .times{@question.answers.new}
  end

  def create
    question_type = QuestionType.new topic_id: Topic.codes[:grammar]
    @question = question_type.questions.build question_params
    if @question.save
      flash[:success] = t ".flash_success"
      redirect_to admin_reading_reading_questions_url
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update_attributes question_params
      flash[:success] = t ".flash_success"
      redirect_to admin_reading_reading_questions_url
    else
      render :edit
    end
  end

  def destroy
    if @question.question_type&.destroy
      flash[:success] = t ".flash"
    else
      flash[:danger] = t ".flash_danger"
    end
    redirect_to request.referrer || root_url
  end

  private

  def question_params
    params.require(:question).permit :title,
      answers_attributes: [:id, :content, :truth]
  end

  def find_question
    @question = Question.find_by id: params[:id]
    return if @question
    flash[:notice] = t "admin.writing.writing_questions.update.flash_notice"
    redirect_to admin_writing_writing_questions_url
  end

  def not_belong_to_exam
    @question.question_type.exam_id.nil?
  end
end

app/controllers/admin/reading/paragraph_questions_controller.rb
class Admin::Reading::ParagraphQuestionsController < ApplicationController
  layout "admin/application"
  before_action :find_question_type, except: %i(index new create)

  def new
    @question_type = QuestionType.new topic_id: Topic.codes[:paragraph]
    Settings.Admin.paragraph_question.num_question
            .times{@question_type.questions.build}
    @question_type.questions.each do |question|
      Settings.Admin.paragraph_question.num_answer
              .times{question.answers.build}
    end
  end

  def create
    @question_type = QuestionType.new question_type_params
    @question_type.topic_id = Topic.codes[:paragraph]
    if @question_type.save
      flash[:success] = t ".flash_success"
      redirect_to admin_reading_reading_questions_url
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question_type.update_attributes question_type_params
      flash[:success] = t ".flash_success"
      redirect_to admin_reading_reading_questions_url
    else
      render :edit
    end
  end

  private

  def question_type_params
    params.require(:question_type).permit :content,
      questions_attributes: [:id, :title,
      answers_attributes: [:id, :content, :truth]]
  end

  def find_question_type
    @question_type = QuestionType.find_by id: params[:id]
    return if @question_type
    flash[:notice] = t "admin.writing.writing_questions.update.flash_notice"
    redirect_to admin_reading_reading_questions_url
  end
end

app/controllers/admin/reading/reading_exams_controller.rb
class Admin::Reading::ReadingExamsController < ApplicationController
  layout "admin/application"

  def index
    @grammar_exams = GetAllExamByTopic.call Topic.codes[:grammar]
    @sign_exams = GetAllExamByTopic.call Topic.codes[:sign]
    @paragraph_exams = GetAllExamByTopic.call Topic.codes[:paragraph]
    @fill_exams = GetAllExamByTopic.call Topic.codes[:fill]
  end
end

app/controllers/admin/reading/reading_questions_controller.rb
class Admin::Reading::ReadingQuestionsController < ApplicationController
  layout "admin/application"
  before_action :find_question_type, only: %i(destroy)
  before_action :not_belong_to_exam, only: %i(destroy)

  def index
    @question_type_grammar = GetAllQuestionTypeByTopic
                             .call Topic.codes[:grammar]
    @question_type_sign = GetAllQuestionTypeByTopic
                          .call Topic.codes[:sign]
    @question_type_paragraph = GetAllQuestionTypeByTopic
                               .call Topic.codes[:paragraph]
    @question_type_filling = GetAllQuestionTypeByTopic
                             .call Topic.codes[:fill]
  end

  def destroy
    @question_type = QuestionType.find_by id: params[:id]
    @question_type.destroy
    flash[:success] = t ".flash"
    redirect_to request.referrer || root_url
  end

  private

  def find_question_type
    @question_type = QuestionType.find_by id: params[:id]
    return if @question_type
    flash[:notice] = t "admin.writing.writing_questions.update.flash_notice"
    redirect_to admin_listening_listening_questions_url
  end

  def not_belong_to_exam
    @question_type.exam_id.nil?
  end
end

app/controllers/admin/reading/sign_exams_controller.rb
class Admin::Reading::SignExamsController < ApplicationController
end

app/controllers/admin/reading/sign_questions_controller.rb
class Admin::Reading::SignQuestionsController < ApplicationController
  layout "admin/application"
  before_action :find_question, except: %i(new create)
  before_action :not_belong_to_exam, only: %i(destroy)
  before_action :validate_create, only: %i(create)
  before_action :validate_update, only: %i(update)

  def new
    @question = Question.new
    Settings.Admin.sign_question.num_answer
            .times{@question.answers.new}
  end

  def create
    question_type = QuestionType.new topic_id: Topic.codes[:sign]
    @question = question_type.questions.build question_params
    if @question.save
      flash[:success] = t ".flash_success"
      redirect_to admin_reading_reading_questions_url
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update_attributes question_params
      flash[:success] = t ".flash_success"
      redirect_to admin_reading_reading_questions_url
    else
      render :edit
    end
  end

  def destroy
    if @question.question_type&.destroy
      flash[:success] = t ".flash"
    else
      flash[:danger] = t ".flash_danger"
    end
    redirect_to request.referrer || root_url
  end

  private

  def question_params
    params.require(:question).permit :picture,
      answers_attributes: [:id, :content, :truth]
  end

  def find_question
    @question = Question.find_by id: params[:id]
    return if @question
    flash[:notice] = t "admin.writing.writing_questions.update.flash_notice"
    redirect_to admin_writing_writing_questions_url
  end

  def not_belong_to_exam
    @question.question_type.exam_id.nil?
  end

  def validate_create
    return if params[:question][:picture].present?
    flash[:danger] = t ".flash"
    redirect_to new_admin_reading_sign_question_url
  end

  def validate_update
    return if params[:question][:picture].present?
    flash[:danger] = t ".flash"
    redirect_to edit_admin_reading_sign_question_url
  end
end

app/controllers/reading_controller.rb
class ReadingController < ApplicationController
  def index; end

  def show
    @code_topic = params[:id]
  end

  def exams_by_topic
    data = ActiveSupport::JSON.decode request.body.read
    @exams = GetAllExamByTopic.call data["id"]
    @exam_paginate = Kaminari.paginate_array(@exams)
                             .page(data["page"]).per data["per"]
    render json: {
      data: @exam_paginate,
      count: @exams.size
    }
  end

  def work_space
    @id_exam = params[:id]
  end

  def exam_detail
    data = ActiveSupport::JSON.decode request.body.read
    id = data["id"]
    @questions = Exam.find(id).questions
    exam = Exam.find_by id: id
    content = exam.question_types.first.content
    render json: {
      questions: @questions.as_json(include: [:answers]),
      code_topic: exam.topic_id,
      content: content
    }
  end

  def check_answer
    data = CreateInfoAnswers.call ActiveSupport::JSON.decode request.body.read
    render json: {
      number_correct: data[:number_correct],
      ids_correct: data[:ids_correct],
      ids_incorrect: data[:ids_incorrect],
      point_collect: data[:point_collect]
    }
  end
end

app/helpers/admin/reading/grammar_exams_helper.rb
module Admin::Reading::GrammarExamsHelper
  def get_truth_answer question
    Answer.true_answer(question.id).first &. content
  end
end

app/views/admin/reading/grammar_questions/_question.html.erb
<tr>
  <td class="center">
    <label class="pos-rel">
      <input type="checkbox" class="ace" />
      <span class="lbl"></span>
    </label>
  </td>
  <td><%= raw question.title %></td>
  <% question.answers.each do |answer| %>
    <td><%= answer.content %></td>
  <% end %>
  <td>
    <%= t ".answer"%><br/><%= Answer.true_answer(question.id).first&.content %>
  </td>
  <td>
    <div class="hidden-sm hidden-xs btn-group">
      <%= link_to edit_admin_reading_grammar_question_path(question) do %>  
        <button class="btn btn-xs btn-info">
          <i class="ace-icon fa fa-pencil bigger-120"></i>
        </button>
      <% end %>
      <% if not_belong_to_exam(question.question_type) %>
        <%= link_to admin_reading_grammar_question_path(question), method: :delete, data: { confirm: t(".confirm") } do %>
          <button class="btn btn-xs btn-danger">
            <i class="ace-icon fa fa-trash-o bigger-120">
            </i>
          </button>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/admin/reading/grammar_questions/edit.html.erb
<div class="modal-content">
  <div class="modal-header no-padding">
    <div class="table-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <span class="white">&times;</span>
      </button>
      <%= t ".title"%>
    </div>
  </div>
  <%= form_for @question, url: {controller: "grammar_questions", action: "update" }, html: {class: "form-horizontal"}  do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="modal-body no-padding">
      <div class="row container">
        <!-- form them cau hoi -->
        <div class="col-xs-12">
          <!-- PAGE CONTENT BEGINS -->
          <div class="space-6"></div>
          <div class="form-group">
            <label class="col-sm-2 control-label" for="form-field-1-1"><%= t ".question"%></label>
            <div class="col-sm-10">
              <%= f.cktext_area :title, rows: 3 %>
            </div>
          </div>
          <%= f.fields_for :answers do |ff| %>
            <div class="form-group">
              <label class="col-sm-2"><%= t ".option"%> <%= option ff.index %></label>
              <div class="col-sm-8">
                <%= ff.text_field :content, class: "form-control"%>
              </div>
              <div class="col-sm-2">
                <%= ff.check_box :truth, class: "form-control"%> <%= t ".is_answer"%>
              </div>
            </div>
            <div class="col-sm-12"></div>
          <% end %>
          <div class="hr hr-16 hr-dotted"></div>
          <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div>

    <div class="modal-footer no-margin-top">
      <button class="btn btn-sm btn-danger pull-left" data-dismiss="modal">
        <i class="ace-icon fa fa-times"></i>
        <%= t ".close"%>
      </button>
      <button class="btn btn-sm btn-danger pull-left" type= "submit">
        <i class="ace-icon fa fa-check"></i>
        <%= t ".submit"%>
      </button>
    </div>
  <% end %>
</div><!-- /.modal-content -->

app/views/admin/reading/grammar_questions/new.html.erb
<div class="modal-content">
  <div class="modal-header no-padding">
    <div class="table-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <span class="white">&times;</span>
      </button>
      <%= t ".title"%>
    </div>
  </div>
  <%= form_for @question, url: admin_reading_grammar_questions_path, html: {class: "form-horizontal"}  do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="modal-body no-padding">
      <div class="row container">
        <!-- form them cau hoi -->
        <div class="col-xs-12">
          <!-- PAGE CONTENT BEGINS -->
          <div class="space-6"></div>
          <div class="form-group">
            <label class="col-sm-2 control-label" for="form-field-1-1"><%= t ".question"%></label>
            <div class="col-sm-10">
              <%= f.cktext_area :title, rows: 3 %>
            </div>
          </div>
          <%= f.fields_for :answers do |ff| %>
            <div class="form-group">
              <label class="col-sm-2"><%= t ".option"%> <%= option ff.index %></label>
              <div class="col-sm-8">
                <%= ff.text_field :content, class: "form-control"%>
              </div>
              <div class="col-sm-2">
                <%= ff.check_box :truth, class: "form-control"%> <%= t ".is_answer"%>
              </div>
            </div>
            <div class="col-sm-12"></div>
          <% end %>
          <div class="hr hr-16 hr-dotted"></div>
          <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div>

    <div class="modal-footer no-margin-top">
      <button class="btn btn-sm btn-danger pull-left" data-dismiss="modal">
        <i class="ace-icon fa fa-times"></i>
        <%= t ".close"%>
      </button>
      <button class="btn btn-sm btn-danger pull-left" type= "submit">
        <i class="ace-icon fa fa-check"></i>
        <%= t ".submit"%>
      </button>
    </div>
  <% end %>
</div><!-- /.modal-content -->