config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    scope :question do
      namespace :listening, path: "/" do
        resources :listening_questions
        resources :conversation_questions
        resources :picture_questions
      end
      namespace :reading, path: "/" do
        resources :reading_questions
        resources :grammar_questions
        resources :sign_questions
        resources :paragraph_questions
      end
      namespace :writing, path: "/" do
        resources :writing_questions 
        resources :questions
      end
    end
    scope :exam do
      namespace :reading, path: "/" do
        resources :reading_exams
        resources :grammar_exams
      end
      namespace :listening, path: "/" do
        resources :listening_exams
      end
      namespace :writing, path: "/" do
        resources :writing_exams
      end
    end
  end
  get "listening", to: "listening#index"
  get "writing", to: "writing#index"
  get "listening", to: "listening#index"
  get "static_pages", to: "static_pages#index"
  get "reading", to: "reading#index"
  post "reading/exams", to: "reading#exams_by_topic"
  get "reading/show/:id", to: "reading#show"
  get "reading/work_space/:id", to: "reading#work_space"
  post "reading/exam_detail", to: "reading#exam_detail"
  post "reading/check_answer", to: "reading#check_answer"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :true_answer,
    ->(question_id){where(question_id: question_id, truth: 1)}
  mount_uploader :picture, PictureUploader
  scope :ids_truth_for_questions, (lambda do |ids_question|
    where(question_id: ids_question, truth: true).pluck :id
  end)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :question_types
  has_many :questions, through: :question_types
  belongs_to :topic

  validates :name, presence: true

  def number_name_exam
    name.split(" ").last.to_i
  end

  def init_name_exam number
    data_name = name.split " "
    data_name[1] = number.to_s
    data_name.join " "
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :question_type
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers
  validates :title,
    length: {maximum: Settings.validate.question.title.maxlength}
  mount_uploader :picture, PictureUploader

  scope :feed, ->(ids){where question_type_id: ids}
  scope :not_belong_to_exam, (lambda do |topic_code|
    where(question_type_id: QuestionType.not_belong_to_exam(topic_code))
  end)
  scope :get_question_types_ids, (lambda do |question_ids|
    where(id: question_ids)
      .pluck(:question_type_id)
  end)
end

app/models/question_type.rb
class QuestionType < ApplicationRecord
  belongs_to :topic
  belongs_to :exam, optional: true
  has_many :questions, dependent: :destroy

  accepts_nested_attributes_for :questions
  scope :ids_by_topic, (lambda do |topic_id|
    select(:id).where(topic_id: topic_id)
  end)
  scope :not_belong_to_exam, (lambda do |topic_code|
    where(topic_id: topic_code, exam_id: nil)
      .pluck(:id)
  end)
  scope :get_from_question_ids, (lambda do |ids|
    where(id: Question.get_question_types_ids(ids))
  end)
end

app/models/topic.rb
class Topic < ApplicationRecord
  enum code: {grammar: 1, sign: 2, paragraph: 3, fill: 4,
              picture: 5, conversation: 6, writing: 7}
  has_many :exams
  has_many :question_types
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_exams
  has_many :exams, through: :user_exams
end

app/models/user_exam.rb
class UserExam < ApplicationRecord
  belongs_to :exam
  belongs_to :user
  has_many :user_tracks
  has_many :questions, through: :user_tracks
end

app/models/user_track.rb
class UserTrack < ApplicationRecord
  belongs_to :user_exam
  belongs_to :question
  has_one :answer
end

app/controllers/admin/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/admin/reading/grammar_exams_controller.rb
class Admin::Reading::GrammarExamsController < ApplicationController
  layout "admin/application"

  def new
    @grammar_exam = CreateNextExam.call Topic.codes[:grammar]
    @questions_not_in_exam = (Question.not_belong_to_exam Topic.codes[:grammar])
                             .page(params[:page])
                             .per Settings.Admin.grammar_exams.per_page
  end

  def create
    if CreateExam.call grammar_exam_params
      flash[:success] = t ".flash_success"
      redirect_to admin_reading_reading_exams_path
    else
      flash[:danger] = t ".flash_danger"
      redirect_to new_admin_reading_grammar_exam_path
    end
  end

  def destroy
    @exam = Exam.find_by id: params[:id]
    @question_types = @exam.question_types
    return unless @question_types.update_all exam_id: nil
    @exam.destroy
    flash[:success] = t ".flash"
    redirect_to request.referrer || root_url
  end

  private

  def grammar_exam_params
    exam = params.require(:exam)
    {name: exam[:name], question_ids: exam[:question_ids]}
  end
end

app/controllers/admin/reading/sign_exams_controller.rb
class Admin::Reading::SignExamsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  skip_before_action :verify_authenticity_token
  include Admin::Reading::GrammarExamsHelper
end

app/controllers/listening_controller.rb
class ListeningController < ApplicationController
  def index; end
end

app/controllers/reading_controller.rb
class ReadingController < ApplicationController
  def index; end

  def show
    @code_topic = params[:id]
  end

  def exams_by_topic
    data = ActiveSupport::JSON.decode request.body.read
    @exams = GetAllExamByTopic.call data["id"]
    @exam_paginate = Kaminari.paginate_array(@exams)
                             .page(data["page"]).per data["per"]
    render json: {
      data: @exam_paginate,
      count: @exams.size
    }
  end

  def work_space
    @id_exam = params[:id]
  end

  def exam_detail
    data = ActiveSupport::JSON.decode request.body.read
    id = data["id"]
    @questions = Exam.find(id).questions
    exam = Exam.find_by id: id
    content = exam.question_types.first.content
    render json: {
      questions: @questions.as_json(include: [:answers]),
      code_topic: exam.topic_id,
      content: content
    }
  end

  def check_answer
    data = CreateInfoAnswers.call ActiveSupport::JSON.decode request.body.read
    render json: {
      number_correct: data[:number_correct],
      ids_correct: data[:ids_correct],
      ids_incorrect: data[:ids_incorrect],
      point_collect: data[:point_collect]
    }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index; end
end

app/controllers/writing_controller.rb
class WritingController < ApplicationController
  def index; end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
  def not_belong_to_exam question_type
    question_type.exam_id.nil?
  end
end

app/helpers/admin/reading/grammar_exams_helper.rb
module Admin::Reading::GrammarExamsHelper
  def get_truth_answer question
    Answer.true_answer(question.id).first &. content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def option value
    option = {"A" => 0, "B" => 1, "C" => 2, "D" => 3}
    option.key value
  end
end

app/views/layouts/admin/_footer.html.erb
<div class="footer">
  <div class="footer-inner">
    <div class="footer-content">
      <span class="bigger-120">
        <span class="blue bolder">Ace</span>
        Application &copy; 2013-2014
      </span>

      &nbsp; &nbsp;
      <span class="action-buttons">
        <a href="#">
          <i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
        </a>

        <a href="#">
          <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
        </a>

        <a href="#">
          <i class="ace-icon fa fa-rss-square orange bigger-150"></i>
        </a>
      </span>
    </div>
  </div>
</div>

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
  <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
</a>
</div><!-- /.main-container -->
<!-- basic scripts -->
<%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
<% if controller.controller_name == "picture_questions" || controller.controller_name == "sign_questions" %>
  <%= javascript_include_tag "picture_upload" %>
<% else %>
  <%= javascript_include_tag "table_detail"  %>
<% end %>

app/views/layouts/admin/_header.html.erb
<div id="navbar" class="navbar navbar-default navbar-collapse h-navbar ace-save-state">
  <div class="navbar-container ace-save-state" id="navbar-container">
    <div class="navbar-header pull-left">
      <a href="index.html" class="navbar-brand">
        <small>
          <i class="fa fa-leaf"></i>
          <%= t ".title" %>
        </small>
      </a>
    </div>
    <div class="navbar-buttons navbar-header pull-right collapse navbar-collapse" role="navigation">
      <ul class="nav ace-nav">
        <li class="light-blue dropdown-modal user-min">
          <a data-toggle="dropdown" href="#" class="dropdown-toggle">
            <img class="nav-user-photo" src="https://avatars1.githubusercontent.com/u/39292690?s=460&v=4" alt="Jason's Photo" />
            <span class="user-info">
              <small><%= t ".welcome" %></small>
              
            </span>

            <i class="ace-icon fa fa-caret-down"></i>
          </a>

          <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
            <li>
              <a href="#">
                <i class="ace-icon fa fa-cog"></i>
                <%= t ".setting" %>
              </a>
            </li>

            <li>
              <a href="profile.html">
                <i class="ace-icon fa fa-user"></i>
                <%= t ".profile" %>
              </a>
            </li>

            <li class="divider"></li>

            <li>
              <a href="#">
                <i class="ace-icon fa fa-power-off"></i>
                <%= t ".logout" %>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div><!-- /.navbar-container -->
</div>
<div class="main-container ace-save-state" id="main-container">
  <script type="text/javascript">
    try{ace.settings.loadState('main-container')}catch(e){}
  </script>

  <div id="sidebar" class="sidebar h-sidebar navbar-collapse collapse ace-save-state">
    <script type="text/javascript">
      try{ace.settings.loadState('sidebar')}catch(e){}
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
      <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
        <button class="btn btn-success">
          <i class="ace-icon fa fa-signal"></i>
        </button>

        <button class="btn btn-info">
          <i class="ace-icon fa fa-pencil"></i>
        </button>

        <button class="btn btn-warning">
          <i class="ace-icon fa fa-users"></i>
        </button>

        <button class="btn btn-danger">
          <i class="ace-icon fa fa-cogs"></i>
        </button>
      </div>

      <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
        <span class="btn btn-success"></span>

        <span class="btn btn-info"></span>

        <span class="btn btn-warning"></span>

        <span class="btn btn-danger"></span>
      </div>
    </div><!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
      <li class="hover">
        <a href="#" class="dropdown-toggle">
          <i class="menu-icon fa fa-list"></i>
          <span class="menu-text"> <%= t ".exam"%> </span>

          <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
          <li class="hover">
            <a href="tables.html">
              <i class="menu-icon fa fa-caret-right"></i>
              Nghe
            </a>

            <b class="arrow"></b>
          </li>

          <li class="hover">
            <a href="jqgrid.html">
              <i class="menu-icon fa fa-caret-right"></i>
              <%= t ".listen"%>
            </a>

            <b class="arrow"></b>
          </li>
          <li class="hover">
            <a href="jqgrid.html">
              <i class="menu-icon fa fa-caret-right"></i>
              <%= t ".read"%>
            </a>

            <b class="arrow"></b>
          </li>
          <li class="hover">
            <a href="jqgrid.html">
              <i class="menu-icon fa fa-caret-right"></i>
              <%= t ".write"%>
            </a>

            <b class="arrow"></b>
          </li>
        </ul>
      </li>

      <li class="hover">
        <a href="#" class="dropdown-toggle">
          <i class="menu-icon fa fa-question-circle"></i>
          <span class="menu-text"> <%= t ".question"%> </span>

          <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
          <li class="hover">
            <a href="<%= admin_listening_listening_questions_url%>">
              <i class="menu-icon fa fa-caret-right"></i>
              <%= t ".listen"%>
            </a>

            <b class="arrow"></b>
          </li>

          <li class="hover">
            <a href="<%= admin_reading_reading_questions_url%>">
              <i class="menu-icon fa fa-caret-right"></i>
              <%= t ".read"%>
            </a>

            <b class="arrow"></b>
          </li>

          <li class="hover">
            <a href="<%= admin_writing_writing_questions_url%>">
              <i class="menu-icon fa fa-caret-right"></i>
              <%= t ".write"%>
            </a>

            <b class="arrow"></b>
          </li>

          
        </ul>
      </li>
    </ul> <!-- /.nav-list -->
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application",
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
        media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag "application",
        "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js",
        'data-turbolinks-track': 'reload' %>
  </head>
  <body class="no-skin">
    <%= render "layouts/admin/header" %>
      <div class="main-content">
        <div class="main-content-inner">
          <div class="page-content">
            <div class="ace-settings-container" id="ace-settings-container">
              <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
                <i class="ace-icon fa fa-cog bigger-130"></i>
              </div>

              <div class="ace-settings-box clearfix" id="ace-settings-box">
                <div class="pull-left width-50">
                  <div class="ace-settings-item">
                    <div class="pull-left">
                      <select id="skin-colorpicker" class="hide">
                        <option data-skin="no-skin" value="#438EB9">#438EB9</option>
                        <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                        <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                        <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                      </select>
                    </div>
                    <span>&nbsp; Choose Skin</span>
                  </div>

                  <div class="ace-settings-item">
                    <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-navbar" autocomplete="off" />
                    <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
                  </div>

                  <div class="ace-settings-item">
                    <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-sidebar" autocomplete="off" />
                    <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
                  </div>

                  <div class="ace-settings-item">
                    <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-breadcrumbs" autocomplete="off" />
                    <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
                  </div>

                  <div class="ace-settings-item">
                    <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" autocomplete="off" />
                    <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
                  </div>

                  <div class="ace-settings-item">
                    <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-add-container" autocomplete="off" />
                    <label class="lbl" for="ace-settings-add-container">
                      Inside
                      <b>.container</b>
                    </label>
                  </div>
                </div><!-- /.pull-left -->

                <div class="pull-left width-50">
                  <div class="ace-settings-item">
                    <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-hover" autocomplete="off" />
                    <label class="lbl" for="ace-settings-hover"> Submenu on Hover</label>
                  </div>

                  <div class="ace-settings-item">
                    <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-compact" autocomplete="off" />
                    <label class="lbl" for="ace-settings-compact"> Compact Sidebar</label>
                  </div>

                  <div class="ace-settings-item">
                    <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-highlight" autocomplete="off" />
                    <label class="lbl" for="ace-settings-highlight"> Alt. Active Item</label>
                  </div>
                </div><!-- /.pull-left -->
              </div><!-- /.ace-settings-box -->
            </div><!-- /.ace-settings-container -->

            <div class="page-header">
              <h1>
                Home
                <small>
                  <i class="ace-icon fa fa-angle-double-right"></i>
                  Quản lý câu hỏi
                </small>
              </h1>
            </div><!-- /.page-header -->

            <div class="row">
              <div class="col-xs-12">
                <!-- PAGE CONTENT BEGINS -->
                <div class="alert alert-info visible-sm visible-xs">
                  <button type="button" class="close" data-dismiss="alert">
                    <i class="ace-icon fa fa-times"></i>
                  </button>
                  Please note that
                  <span class="blue bolder">top menu style</span>
                  is visible only in devices larger than
                  <span class="blue bolder">991px</span>
                  which you can change using CSS builder tool.
                </div>

                <div class="well well-sm visible-sm visible-xs">
                  Top menu can become any of the 3 mobile view menu styles:
                  <em>default</em>

                  <em>collapsible</em>
                  or
                  <em>minimized</em>.
                </div>

                <div class="hidden-sm hidden-xs">
                  <button type="button" class="sidebar-collapse btn btn-white btn-primary" data-target="#sidebar">
                    <i class="ace-icon fa fa-angle-double-up" data-icon1="ace-icon fa fa-angle-double-up" data-icon2="ace-icon fa fa-angle-double-down"></i>
                    Collapse/Expand Menu
                  </button>
                </div>
                <br/>
                <div class="center">
                  <div class="col-sm-12">
                    <% flash.each do |message_type, message| %>
                      <div class="alert alert-<%= message_type %>">
                        <button type="button" class="close" data-dismiss="alert">
                          <i class="ace-icon fa fa-times"></i>
                        </button>
                        <%= message %>
                        </br>
                      </div>
                    <% end %>
                  </div>
                  <div class="col-sm-12"><%= yield %></div><!-- /.col -->
                </div>

                <!-- PAGE CONTENT ENDS -->
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.page-content -->
        </div>
      </div><!-- /.main-content -->
    <%= render "layouts/admin/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".message" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>